### ISSUE TITLE
Cannot generate graph for some replays..?

### ISSUE THREAD

**Issue by Leinadix** [adgjl7777777/VSRG_Total_Analyzer#1]
```\VSRT_Total_Analyzer_v0.1>pressingtime.exe
Leinadix
Traceback (most recent call last):
  File "pressingtime.py", line 93, in <module>
  File "pressingtime.py", line 85, in presssaver
  File "matplotlib\pyplot.py", line 859, in savefig
  File "matplotlib\figure.py", line 2311, in savefig
  File "matplotlib\backends\backend_qt5agg.py", line 81, in print_figure
  File "matplotlib\backend_bases.py", line 2150, in print_figure
  File "matplotlib\backend_bases.py", line 2079, in _get_output_canvas
ValueError: Format '3x] (2023-06-25) osumania' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)
[32676] Failed to execute script 'pressingtime' due to unhandled exception!```

Replays to reproduce with (containing two scores made by me):
[Replays.zip](https://github.com/adgjl7777777/VSRG_Total_Analyzer/files/12251417/Replays.zip)

**Comment by adgjl7777777** [comment]
That's because there's "." in the replay file. For example: Quaraphinix_1.5x.osr
Please remove that dot to run program file properly

Actually I have improved version of this program, I will upload it soon
That version is already fixed the issue
